@HOST = http://127.0.0.1:10800

###
GET {{HOST}}/health-check HTTP/1.1

###
GET {{HOST}}/cat HTTP/1.1

###
GET {{HOST}}/cat/844b3871-152f-4d63-8a02-44119623e5f7 HTTP/1.1

###
POST {{HOST}}/cat HTTP/1.1
Content-Type: application/json

{
    "msg": "MuMeowMimi"
}

###

PUT {{HOST}}/844b3871-152f-4d63-8a02-44119623e5f7 HTTP/1.1
Content-Type: application/json  

{
    "msg": "MuMeowMimi"
}

###

DELETE {{HOST}}/844b3871-152f-4d63-8a02-44119623e5f7 HTTP/1.1
